"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      "decks",
      [
        {
          user_id: 1,
          author_id: 1,
          language_id: 10,
          difficulty_level_id: 3,
          n_likes: 1,
          n_forks: 1,
          non_public: false,
          ai_generated: false,
          created_at: new Date("2023-05-11"),
          updated_at: new Date("2023-05-11"),
        },
        {
          user_id: 1,
          author_id: 1,
          language_id: 59,
          difficulty_level_id: 1,
          n_likes: 0,
          n_forks: 1,
          non_public: false,
          ai_generated: false,
          created_at: new Date("2023-05-11"),
          updated_at: new Date("2023-05-11"),
        },
        {
          user_id: 2,
          author_id: 1,
          language_id: 10,
          difficulty_level_id: 2,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: false,
          created_at: new Date("2023-05-12"),
          updated_at: new Date("2023-05-12"),
        },
        {
          user_id: 2,
          author_id: 2,
          language_id: 59,
          difficulty_level_id: 1,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-12"),
          updated_at: new Date("2023-05-12"),
        },
        {
          user_id: 2,
          author_id: 2,
          language_id: 59,
          difficulty_level_id: 2,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: true,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          user_id: 2,
          author_id: 1,
          language_id: 59,
          difficulty_level_id: 1,
          n_likes: 0,
          n_forks: 1,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-13"),
          updated_at: new Date("2023-05-13"),
        },
        {
          user_id: 3,
          author_id: 3,
          language_id: 19,
          difficulty_level_id: 2,
          n_likes: 0,
          n_forks: 1,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-13"),
          updated_at: new Date("2023-05-13"),
        },
        {
          user_id: 3,
          author_id: 3,
          language_id: 59,
          difficulty_level_id: 1,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-14"),
          updated_at: new Date("2023-05-14"),
        },
        {
          user_id: 1,
          author_id: 1,
          language_id: 10,
          difficulty_level_id: 2,
          n_likes: 0,
          n_forks: 1,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-14"),
          updated_at: new Date("2023-05-14"),
        },
        {
          user_id: 2,
          author_id: 1,
          language_id: 10,
          difficulty_level_id: 2,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-15"),
          updated_at: new Date("2023-05-15"),
        },
        {
          user_id: 1,
          author_id: 2,
          language_id: 59,
          difficulty_level_id: 1,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-15"),
          updated_at: new Date("2023-05-15"),
        },
        {
          user_id: 5,
          author_id: 3,
          language_id: 19,
          difficulty_level_id: 2,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-16"),
          updated_at: new Date("2023-05-16"),
        },
        {
          user_id: 5,
          author_id: 3,
          language_id: 19,
          difficulty_level_id: 3,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-16"),
          updated_at: new Date("2023-05-16"),
        },
        {
          user_id: 6,
          author_id: 6,
          language_id: 15,
          difficulty_level_id: 5,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-16"),
          updated_at: new Date("2023-05-16"),
        },
        {
          user_id: 6,
          author_id: 6,
          language_id: 15,
          difficulty_level_id: 5,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-16"),
          updated_at: new Date("2023-05-16"),
        },
        {
          user_id: 6,
          author_id: 6,
          language_id: 15,
          difficulty_level_id: 5,
          n_likes: 0,
          n_forks: 0,
          non_public: false,
          ai_generated: null,
          created_at: new Date("2023-05-16"),
          updated_at: new Date("2023-05-16"),
        },
      ],
      {}
    );
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete("decks", null, {});
  },
};
