"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      "cards",
      [
        // Deck one: Chinese intermediate
        {
          user_id: 1,
          deck_id: 1,
          front: "悲惨",
          back: "Sad, miserable (bēi cǎn)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "翠",
          back: "Emrald green (cuì)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "仿佛",
          back: "Just like, as if (fǎng fú)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "赤",
          back: "Red (chì)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "湛蓝",
          back: "Pure blue, especially for describing the sky or the ocean (zhàn lán)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "墨",
          back: "Ink, or ink black (mò)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "衬衫",
          back: "Shirt (chèn shān)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "叮嘱",
          back: "To urge repeatedly (dīng zhǔ)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "熟悉",
          back: "Familiar (shú xī)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "欧洲",
          back: "Europe (ōu zhōu)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "邀宠",
          back: "Courting favor with powerful individuals (yāo chǒng)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        {
          user_id: 1,
          deck_id: 1,
          front: "勤勉",
          back: "Diligent, industrious (qín miǎn)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-19"),
          created_at: new Date("2023-04-01"),
          updated_at: new Date("2023-04-01"),
        },
        // Deck two: Swedish beginner
        {
          user_id: 1,
          deck_id: 3,
          front: "stor",
          back: "big",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-20"),
          created_at: new Date("2023-04-03"),
          updated_at: new Date("2023-04-03"),
        },
        {
          user_id: 1,
          deck_id: 3,
          front: "lång",
          back: "long",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-20"),
          created_at: new Date("2023-04-03"),
          updated_at: new Date("2023-04-03"),
        },
        {
          user_id: 1,
          deck_id: 3,
          front: "trött",
          back: "tired",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-20"),
          created_at: new Date("2023-04-03"),
          updated_at: new Date("2023-04-03"),
        },
        {
          user_id: 1,
          deck_id: 3,
          front: "liten",
          back: "small",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-20"),
          created_at: new Date("2023-04-03"),
          updated_at: new Date("2023-04-03"),
        },
        {
          user_id: 1,
          deck_id: 3,
          front: "litet",
          back: "small",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-20"),
          created_at: new Date("2023-04-03"),
          updated_at: new Date("2023-04-03"),
        },
        {
          user_id: 1,
          deck_id: 3,
          front: "små",
          back: "small",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-20"),
          created_at: new Date("2023-04-03"),
          updated_at: new Date("2023-04-03"),
        },
        {
          user_id: 1,
          deck_id: 3,
          front: "lilla",
          back: "small (plural)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-04-20"),
          created_at: new Date("2023-04-03"),
          updated_at: new Date("2023-04-03"),
        },
        // Deck three: Chinese beginner (forked from deck one)
        {
          user_id: 2,
          deck_id: 2,
          front: "悲伤",
          back: "Sad (bēi shāng)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-05-02"),
          created_at: new Date("2023-05-01"),
          updated_at: new Date("2023-05-01"),
        },
        {
          user_id: 2,
          deck_id: 2,
          front: "绿色",
          back: "Green (lǜ sè)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-05-02"),
          created_at: new Date("2023-05-01"),
          updated_at: new Date("2023-05-01"),
        },
        {
          user_id: 2,
          deck_id: 2,
          front: "红色",
          back: "Red (hóng sè)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-05-02"),
          created_at: new Date("2023-05-01"),
          updated_at: new Date("2023-05-01"),
        },
        {
          user_id: 2,
          deck_id: 2,
          front: "蓝色",
          back: "Blue (lán sè)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-05-02"),
          created_at: new Date("2023-05-01"),
          updated_at: new Date("2023-05-01"),
        },
        {
          user_id: 2,
          deck_id: 2,
          front: "黑色",
          back: "Black (hēi sè)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-05-02"),
          created_at: new Date("2023-05-01"),
          updated_at: new Date("2023-05-01"),
        },
        {
          user_id: 2,
          deck_id: 2,
          front: "衬衫",
          back: "Shirt (chèn shān)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-05-02"),
          created_at: new Date("2023-05-01"),
          updated_at: new Date("2023-05-01"),
        },
        {
          user_id: 2,
          deck_id: 2,
          front: "欧洲",
          back: "Europe (ōu zhōu)",
          number_of_times_seen: 0,
          number_of_times_correct: 0,
          last_seen: new Date("2023-05-02"),
          created_at: new Date("2023-05-01"),
          updated_at: new Date("2023-05-01"),
        },
      ],
      {}
    );
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete("cards", null, {});
  },
};
